ATPG: atpg.cpp File Reference
atpg.cpp File Reference
#include <iostream>
#include "atpg.hpp"
#include "CmdLine.h"
Functions
void processCmdLine (CmdLine &cL, int argc, char **argv)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Outline of source file organization SUBSYSTEM | SOURCE FILES ------------------------—+--------------------------------------— Command line | CmdLine.h, CmdLine.cpp Program tracing | Debug.hpp Multi-valued logic | DLogic.hpp Graph visualization and IO | modifications to Graphviz.hpp Driver program | atpg.cpp EDA algorithm - basic DFT | atpg.hpp, DFrontier.hpp
INCLUSION TREE (-+-> means "includes") -atpg.cpp -+->CmdLine.h |->atpg.hpp -+->Debug.hpp --—+->Debug.cpp –+->Debug.h |->DFrontier.hpp |->DLogic.hpp —+->DLogic.h | |->DLogic.cpp |->BGL headers |->STL headers -CmdLine.cpp -+->CmdLine.h
Template code have the prefix .hpp for two reasons. Firstly, Boost code uses .hpp, so I follow the convention. Secondly, the VC6 IDE will separately compile a .cpp regardless of whether it is in the Source or Header folders. Using .hpp prevents this over-eager compilation.
Definition at line 24 of file atpg.cpp.
References SupportGraph::Digraph, SupportGraph::getDotFileType(), RunGraph< GraphType >::getVersion(), SupportGraph::Graph, RunGraph< GraphType >::initializeGraph(), CmdLine::printSwitches(), processCmdLine(), RunGraph< GraphType >::runATPG(), RunGraph< GraphType >::setDebug(), CmdLine::switchValue(), RunGraph< GraphType >::test(), and RunGraph< GraphType >::writeGraph().
void processCmdLine (CmdLine & cL, int argc, char ** argv)
Definition at line 14 of file atpg.cpp.
References CmdLine::addParameterSwitch(), CmdLine::addStandaloneSwitch(), and CmdLine::process().
Referenced by main().