ATPG: NodeHelper Class Reference
NodeHelper Class Reference
#include <atpg.hpp>
Public Member Functions
NodeHelper (const string &label)
void setName (const string &name)
void setFunc (const string &func)
const string & getName ()
const string & getFunc ()
Detailed Description
Definition at line 575 of file atpg.hpp.
Constructor & Destructor Documentation
NodeHelper::NodeHelper (const string & label) inline
Definition at line 582 of file atpg.hpp.
References setFunc(), and setName().
Member Function Documentation
const string& NodeHelper::getFunc () inline
Definition at line 595 of file atpg.hpp.
Referenced by BacktraceVisitor< GraphType >::discover_vertex(), RunGraph< GraphType >::propagateChange(), and BacktraceVisitor< GraphType >::suggestEnablingSignal().
const string& NodeHelper::getName () inline
Definition at line 594 of file atpg.hpp.
void NodeHelper::setFunc (const string & func) inline
Definition at line 593 of file atpg.hpp.
Referenced by NodeHelper().
void NodeHelper::setName (const string & name) inline
Definition at line 592 of file atpg.hpp.
Referenced by NodeHelper().
The documentation for this class was generated from the following file:
atpg.hpp