ATPG: RunGraph< GraphType > Class Template Reference
RunGraph< GraphType > Class Template Reference
#include <atpg.hpp>
Public Types
typedef boost::property_map
< GraphType,
boost::vertex_attribute_t >
::type VertexAttrMapType
typedef boost::property_map
< GraphType,
boost::edge_attribute_t >
::type EdgeAttrMapType
typedef boost::graph_traits
< GraphType >
::vertex_descriptor VertexType
typedef boost::graph_traits
< GraphType >::vertex_iterator VertexIteratorType
typedef boost::graph_traits
< GraphType >::edge_iterator EdgeIteratorType
typedef boost::graph_traits
< GraphType >
::in_edge_iterator InEdgeIteratorType
typedef boost::graph_traits
< GraphType >
::out_edge_iterator OutEdgeIteratorType
typedef std::deque< VertexType > DFrontierType
typedef std::deque< VertexType > PropagateContainerType
typedef set< VertexSignalPair
< VertexType > > SetVertexSignalPairType
Public Member Functions
BOOST_STATIC_ASSERT ((boost::is_same< GraphType, GraphvizGraph >::value||boost::is_same< GraphType, GraphvizDigraph >::value))
RunGraph (const string &path)
~RunGraph ()
void setDebug (const string &dString)
void initializeGraph ()
void backtraceVertex (const VertexType &v)
bool processOutput (VertexType v, GraphType &g, PropagateContainerType &cv, DLogic outS, DLogic currentS)
tripleBool propagateChange (VertexType v, GraphType &g, PropagateContainerType &cv)
tripleBool propagateVertex (VertexType v, DLogic driveSignal)
void runATPG ()
void test (const string &startLabel)
VertexType endVertex ()
VertexType findVertexWithLabel (const string &label)
void writeGraph (const string &path)
void seedDFrontier (DFrontierType &dF)
void updateDFrontier (DFrontierType &dF)
void printFinishStats (bool DFrontierEmpty, bool FirstOutputFound, bool FirstNonDPassable, bool FirstInconsistentOutput)
const char * getVersion ()
Static Public Attributes
static char * _Version ="$Id$"
Detailed Description
template<class GraphType>
class RunGraph< GraphType >
Definition at line 604 of file atpg.hpp.
Member Typedef Documentation
template<class GraphType> typedef std::deque<VertexType> RunGraph< GraphType >::DFrontierType
Definition at line 615 of file atpg.hpp.
template<class GraphType> typedef boost::property_map<GraphType,boost::edge_attribute_t>::type RunGraph< GraphType >::EdgeAttrMapType
Definition at line 609 of file atpg.hpp.
template<class GraphType> typedef boost::graph_traits<GraphType>::edge_iterator RunGraph< GraphType >::EdgeIteratorType
Definition at line 612 of file atpg.hpp.
template<class GraphType> typedef boost::graph_traits<GraphType>::in_edge_iterator RunGraph< GraphType >::InEdgeIteratorType
Definition at line 613 of file atpg.hpp.
template<class GraphType> typedef boost::graph_traits<GraphType>::out_edge_iterator RunGraph< GraphType >::OutEdgeIteratorType
Definition at line 614 of file atpg.hpp.
template<class GraphType> typedef std::deque<VertexType> RunGraph< GraphType >::PropagateContainerType
Definition at line 616 of file atpg.hpp.
template<class GraphType> typedef set<VertexSignalPair<VertexType> > RunGraph< GraphType >::SetVertexSignalPairType
Definition at line 617 of file atpg.hpp.
template<class GraphType> typedef boost::property_map<GraphType,boost::vertex_attribute_t>::type RunGraph< GraphType >::VertexAttrMapType
Definition at line 608 of file atpg.hpp.
template<class GraphType> typedef boost::graph_traits<GraphType>::vertex_iterator RunGraph< GraphType >::VertexIteratorType
Definition at line 611 of file atpg.hpp.
template<class GraphType> typedef boost::graph_traits<GraphType>::vertex_descriptor RunGraph< GraphType >::VertexType
Definition at line 610 of file atpg.hpp.
Constructor & Destructor Documentation
template<typename G > RunGraph< G >::RunGraph (const string & path)
Definition at line 655 of file atpg.hpp.
template<typename G > RunGraph< G >::~RunGraph ()
Definition at line 665 of file atpg.hpp.
Member Function Documentation
template<typename G > void RunGraph< G >::backtraceVertex (const VertexType & v)
Definition at line 752 of file atpg.hpp.
References Debug::Dbg().
template<class GraphType> RunGraph< GraphType >::BOOST_STATIC_ASSERT ((boost::is_same< GraphType, GraphvizGraph >::value||boost::is_same< GraphType, GraphvizDigraph >::value))
template<class GraphType> VertexType RunGraph< GraphType >::endVertex () inline
Definition at line 633 of file atpg.hpp.
template<typename G > RunGraph< G >::VertexType RunGraph< G >::findVertexWithLabel (const string & label)
Definition at line 674 of file atpg.hpp.
template<class GraphType> const char* RunGraph< GraphType >::getVersion () inline
Definition at line 639 of file atpg.hpp.
References RunGraph< GraphType >::_Version.
Referenced by main().
template<typename G > void RunGraph< G >::initializeGraph ()
Definition at line 745 of file atpg.hpp.
Referenced by main().
template<typename G > void RunGraph< G >::printFinishStats (bool DFrontierEmpty, bool FirstOutputFound, bool FirstNonDPassable, bool FirstInconsistentOutput)
Definition at line 728 of file atpg.hpp.
template<typename G> bool RunGraph< G >::processOutput (VertexType v, G & g, PropagateContainerType & cv, DLogic outS, DLogic currentS)
Definition at line 786 of file atpg.hpp.
References DLogic::_D, DLogic::D, Debug::Dbg(), OutputConsistent(), putDescendantsInDFrontier(), putDescendantsInPContainer(), setOutputEdges(), and DLogic::X.
template<typename G> tripleBool RunGraph< G >::propagateChange (VertexType v, G & g, PropagateContainerType & cv)
Definition at line 802 of file atpg.hpp.
References Debug::Dbg(), DPassable(), EvaluateMultipleInputs(), EvaluateOutputs(), EvaluateSingleInput(), NodeHelper::getFunc(), DLogic::GetString(), and DLogic::X.
template<typename G > tripleBool RunGraph< G >::propagateVertex (VertexType v, DLogic driveSignal)
Definition at line 763 of file atpg.hpp.
References Debug::Dbg(), and setOutputEdges().
template<typename G > void RunGraph< G >::runATPG ()
Main call tree for runATPG
runATPG –+–> initializeGraph +–> seedDFrontier +–> backtraceVertex –+–> BacktraceVisitor | +–> depth_first_visit +–> propagateVertex –+–> propagateChange –+–> EvaluateOutputs | +–> EvaluateSingleInput | +–> GetSignalFunctor | +–> EvaluateMultipleInputs | +–> processOutput +–> printFinishStats Algorithm descrition for runATPG
The overall control logic is implemented in the member function testATPG.
In step (0), a fault is either a D or a _D on some edge. A D means that a good circuit shows a ONE, while the faulty circuit shows a ZERO. This is called a stuck-at-zero fault. Similarly, a _D represents a stuck-at-one fault.
As the simulation proceeds, the fault will be propagated from one node to another until it hopefully reaches an output node. This means that the fault signal D or _D will pass along the path until it reaches the output node.
At any time, the nodes whose inputs are D or _D are collectively called the D Frontier. During simulation, this D Frontier fans out until they encounter an output node. The D Frontier is implemented in the class DFrontier.
Initially, the only vertex in the D Frontier is the vertex whose input is the fault to be simulated. This is implemented in the function seedDFrontier.
As the simulation progresses, more vertices are added to the D Frontier as the D or _D gets passed along to connected vertices. Also, vertices are removed from the D Frontier when their D or _D inputs are evaluated, and outputs updated.
In step (1), the backtracing is easy to implement with BGL's reverse_graph. In this implementation, I chose to skip the D or _D edge itself and only backtrace the remaining unknown edges back to their inputs. This is done using BGL's depth_first_visit with a custom BacktraceVisitor.
When an input vertex is found, we select a logic value, either ONE or ZERO to simulate it. A suggested logic value is obtained by examining all the vertices driven by this input, and using the enabling values of the vertices' functionality. For example, if an input is connected to a nand gate, the enabling value of a nand is ONE. If an input is connected to a nor gate, the enabling value is ZERO.
In step (2), t prevents this. he simulation is implemented with propagateVertex call. The propagateVertex uses a container of vertices to keep track of pending changes. This is because a vertex may be updated several times depending on when inputs arrive. The standard DFS or BFS is designed to visit each vertex once, and so will not propagate all the inputs correctly.
Step (3) is again implemented in propagateVertex. Termination conditions While the book [5] does not describe this in detail, there are two situations in which the algorithm will terminate.
1) It is possible that a fault in the circuit is not observable. The algorithm terminates when the D Frontier is empty.
A circuit may be non observable structurally, ie there are no output nodes traceable from the fault. This means we will never reach an output node.
A circuit may also be non observable because the specific fault cannot be propagated. This means that before we reach an output node, the fault propagation is blocked because of a controlling input somewhere along the path. An example is the sample input 2.dot, which differs from the demo circuit Not2.dot only in the seed fault is _D instead of D.
2) If a fault is observable, we should be able to see the path of D propagation to the output node.
As part of my investigation, the conditions for termination are kept tracked of. These are :
an output node is found
the D path is blocked
an inconsistent output is found.
DFrontier being empty
The first 3 are the tripleBool returned from propagateChange, while an empty D Frontier can be queried from the DFrontier data structure.
These states are printed out at the end of the run, in printFinishStats so that better understand of the current algorithm and its behavior on different circuits can be studied.
Definition at line 951 of file atpg.hpp.
References dumpSetVS().
Referenced by main().
template<typename G > void RunGraph< G >::seedDFrontier (DFrontierType & dF)
Definition at line 684 of file atpg.hpp.
References dumpDFrontier().
template<typename G > void RunGraph< G >::setDebug (const string & dString)
Definition at line 741 of file atpg.hpp.
References Debug::specify().
Referenced by main().
template<typename G > void RunGraph< G >::test (const string & startLabel)
Definition at line 976 of file atpg.hpp.
Referenced by main().
template<typename G > void RunGraph< G >::updateDFrontier (DFrontierType & dF)
Definition at line 707 of file atpg.hpp.
References Debug::Dbg(), and dumpDFrontier().
template<typename G > void RunGraph< G >::writeGraph (const string & path)
Definition at line 669 of file atpg.hpp.
Referenced by main().
Member Data Documentation
template<class GraphType> char * RunGraph< G >::_Version ="$Id$" static
Definition at line 639 of file atpg.hpp.
Referenced by RunGraph< GraphType >::getVersion().
The documentation for this class was generated from the following file:
atpg.hpp