ATPG: CmdLine Class Reference
CmdLine Class Reference
#include <CmdLine.h>
Public Member Functions
CmdLine ()
void addParameterSwitch (const STD string flag, const STD string initialValue, const STD string help)
void addStandaloneSwitch (const STD string flag, const STD string help)
const STD string & switchValue (const STD string flag)
const STD string & switchHelp (const STD string flag)
void process (int argc, char **argv)
int NumberOfRemainingParameters ()
const char * RemainingParameter (int index)
void printSwitches (STD ostream &s=STD cout)
void dump (STD ostream &s=STD cout) const
void dump (STD ostream &s=STD cout)
Friends
STD ostream & operator<< (STD ostream &s, const CmdLine &c)
Detailed Description
Definition at line 20 of file CmdLine.h.
Constructor & Destructor Documentation
CmdLine::CmdLine ()
Definition at line 11 of file CmdLine.cpp.
Member Function Documentation
void CmdLine::addParameterSwitch (const STD string flag, const STD string initialValue, const STD string help)
Definition at line 14 of file CmdLine.cpp.
Referenced by processCmdLine().
void CmdLine::addStandaloneSwitch (const STD string flag, const STD string help)
Definition at line 18 of file CmdLine.cpp.
Referenced by processCmdLine().
void CmdLine::dump (STD ostream & s = STD cout) const
Referenced by operator<<().
void CmdLine::dump (STD ostream & s = STD cout)
int CmdLine::NumberOfRemainingParameters ()
Definition at line 47 of file CmdLine.cpp.
void CmdLine::printSwitches (STD ostream & s = STD cout)
Definition at line 54 of file CmdLine.cpp.
Referenced by main().
void CmdLine::process (int argc, char ** argv)
Definition at line 27 of file CmdLine.cpp.
Referenced by processCmdLine().
const char * CmdLine::RemainingParameter (int index)
Definition at line 50 of file CmdLine.cpp.
const string & CmdLine::switchHelp (const STD string flag)
Definition at line 24 of file CmdLine.cpp.
const string & CmdLine::switchValue (const STD string flag)
Definition at line 21 of file CmdLine.cpp.
Referenced by main().
Friends And Related Function Documentation
STD ostream& operator<< (STD ostream & s, const CmdLine & c) friend
The documentation for this class was generated from the following files:
CmdLine.h
CmdLine.cpp