ATPG: Debug Class Reference
Debug Class Reference
#include <debug.h>
Public Member Functions
Debug (const char *f, bool rawtimeMode=false, bool bEndLine=false)
~Debug ()
void Dbg (const STD string &keyword, const STD string &description, char *pC)
template<class T >
void Dbg (const STD string &keyword, const STD string &description, const T *pT)
template<class T >
void Dbg (const STD string &keyword, const STD string &description, const T &tValue)
void Dbg (const STD string &keyword, char *pC)
template<class T >
void Dbg (const STD string &keyword, const T *pT)
template<class T >
void Dbg (const STD string &keyword, const T &tValue)
Static Public Member Functions
static void specify (const char *)
static void TimeStart (const STD string &, const char *)
static void TimeEnd (const STD string &, const char *)
static void Sync ()
Detailed Description
Definition at line 508 of file debug.h.
Constructor & Destructor Documentation
Debug::Debug (const char * f, bool rawtimeMode = false, bool bEndLine = false)
Definition at line 82 of file debug.cpp.
References Debug().
Referenced by Debug().
Debug::~Debug ()
Definition at line 90 of file debug.cpp.
Member Function Documentation
void Debug::Dbg (const STD string & keyword, const STD string & description, char * pC)
Referenced by RunGraph< GraphType >::backtraceVertex(), BacktraceVisitor< GraphType >::discover_vertex(), dumpDFrontier(), dumpSetVS(), EvaluateMultipleInputs(), EvaluateOutputs(), EvaluateSingleInput(), BacktraceVisitor< GraphType >::HasXs(), RunGraph< GraphType >::processOutput(), RunGraph< GraphType >::propagateChange(), RunGraph< GraphType >::propagateVertex(), putDescendantsInPContainer(), BacktraceVisitor< GraphType >::suggestEnablingSignal(), and RunGraph< GraphType >::updateDFrontier().
template<class T > void Debug::Dbg (const STD string & keyword, const STD string & description, const T * pT) inline
Definition at line 517 of file debug.h.
template<class T > void Debug::Dbg (const STD string & keyword, const STD string & description, const T & tValue) inline
Definition at line 526 of file debug.h.
void Debug::Dbg (const STD string & keyword, char * pC)
template<class T > void Debug::Dbg (const STD string & keyword, const T * pT) inline
Definition at line 532 of file debug.h.
template<class T > void Debug::Dbg (const STD string & keyword, const T & tValue) inline
Definition at line 542 of file debug.h.
void Debug::specify (const char * opt) static
Definition at line 322 of file debug.cpp.
References CLEAR.
Referenced by RunGraph< GraphType >::setDebug().
void Debug::Sync () static
Definition at line 292 of file debug.cpp.
void Debug::TimeEnd (const STD string & , const char *) static
Definition at line 262 of file debug.cpp.
void Debug::TimeStart (const STD string & , const char *) static
Definition at line 242 of file debug.cpp.
The documentation for this class was generated from the following files:
debug.h
debug.cpp