ATPG: BacktraceVisitor< GraphType > Class Template Reference
BacktraceVisitor< GraphType > Class Template Reference
#include <atpg.hpp>
Public Types
typedef boost::property_map
< GraphType,
boost::vertex_attribute_t >
::const_type ConstVertexAttrMapType
typedef boost::property_map
< GraphType,
boost::edge_attribute_t >
::type EdgeAttrMapType
typedef boost::graph_traits
< GraphType >
::in_edge_iterator InEdgeIteratorType
typedef boost::graph_traits
< GraphType >
::out_edge_iterator OutEdgeIteratorType
typedef boost::graph_traits
< GraphType >
::vertex_descriptor VertexType
typedef set< VertexSignalPair
< VertexType > > SetVertexSignalPairType
Public Member Functions
BacktraceVisitor (const GraphType &g, EdgeAttrMapType &eM, SetVertexSignalPairType &setVS)
template<class Vertex , class GraphType >
bool HasXs (Vertex v, const GraphType &g)
template<class Vertex , class GraphType >
DLogic suggestEnablingSignal (Vertex v, const GraphType &g)
template<class Vertex , class GraphType >
void discover_vertex (Vertex v, const GraphType &g)
Detailed Description
template<typename GraphType>
class BacktraceVisitor< GraphType >
Definition at line 479 of file atpg.hpp.
Member Typedef Documentation
template<typename GraphType> typedef boost::property_map<GraphType,boost::vertex_attribute_t>::const_type BacktraceVisitor< GraphType >::ConstVertexAttrMapType
Definition at line 488 of file atpg.hpp.
template<typename GraphType> typedef boost::property_map<GraphType,boost::edge_attribute_t>::type BacktraceVisitor< GraphType >::EdgeAttrMapType
Definition at line 489 of file atpg.hpp.
template<typename GraphType> typedef boost::graph_traits<GraphType>::in_edge_iterator BacktraceVisitor< GraphType >::InEdgeIteratorType
Definition at line 490 of file atpg.hpp.
template<typename GraphType> typedef boost::graph_traits<GraphType>::out_edge_iterator BacktraceVisitor< GraphType >::OutEdgeIteratorType
Definition at line 491 of file atpg.hpp.
template<typename GraphType> typedef set<VertexSignalPair<VertexType> > BacktraceVisitor< GraphType >::SetVertexSignalPairType
Definition at line 493 of file atpg.hpp.
template<typename GraphType> typedef boost::graph_traits<GraphType>::vertex_descriptor BacktraceVisitor< GraphType >::VertexType
Definition at line 492 of file atpg.hpp.
Constructor & Destructor Documentation
template<typename GraphType> BacktraceVisitor< GraphType >::BacktraceVisitor (const GraphType & g, EdgeAttrMapType & eM, SetVertexSignalPairType & setVS) inline
Definition at line 495 of file atpg.hpp.
Member Function Documentation
template<typename GraphType> template<class Vertex , class GraphType > void BacktraceVisitor< GraphType >::discover_vertex (Vertex v, const GraphType & g) inline
Definition at line 553 of file atpg.hpp.
References Debug::Dbg(), NodeHelper::getFunc(), BacktraceVisitor< GraphType >::HasXs(), and BacktraceVisitor< GraphType >::suggestEnablingSignal().
template<typename GraphType> template<class Vertex , class GraphType > bool BacktraceVisitor< GraphType >::HasXs (Vertex v, const GraphType & g) inline
Definition at line 498 of file atpg.hpp.
References Debug::Dbg().
Referenced by BacktraceVisitor< GraphType >::discover_vertex().
template<typename GraphType> template<class Vertex , class GraphType > DLogic BacktraceVisitor< GraphType >::suggestEnablingSignal (Vertex v, const GraphType & g) inline
Definition at line 515 of file atpg.hpp.
References Debug::Dbg(), NodeHelper::getFunc(), DLogic::GetString(), DLogic::ONE, and DLogic::ZERO.
Referenced by BacktraceVisitor< GraphType >::discover_vertex().
The documentation for this class was generated from the following file:
atpg.hpp